include_guard()

include(${CMAKE_CURRENT_LIST_DIR}/Fausty.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ImGui.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Sdl.cmake)

if(${SHELL_PLATFORM} STREQUAL "Windows")
  if(${SHELL_BACKEND} STREQUAL "Gl3")
    set(SHELL_HEADER "<fausty/shell/platform/windows/gl3/gl3_window.h>")
    set(SHELL_CLASS "Gl3Window")
  elseif(${SHELL_BACKEND} STREQUAL "Dx12")
    set(SHELL_HEADER "<fausty/shell/platform/windows/dx12/dx12_window.h>")
    set(SHELL_CLASS "Dx12Window")
  endif()
elseif(${SHELL_PLATFORM} STREQUAL "X11")
    set(SHELL_HEADER "<fausty/shell/platform/x11/x11_window.h>")
    set(SHELL_CLASS "X11Window")
endif()

function(USES_SHELL THIS)
USES_FAUSTY(${THIS})
USES_IMGUI(${THIS})
USES_SDL(${THIS})
target_compile_definitions(${THIS} PRIVATE SHELL_HEADER=${SHELL_HEADER} SHELL_CLASS=${SHELL_CLASS})
target_include_directories(${THIS} PRIVATE ${FAUSTY_ROOT}/src)
#target_link_libraries(${THIS} PRIVATE ImGui FaustyShell${SHELL_PLATFORM}${SHELL_BACKEND})
target_link_libraries(${THIS} PRIVATE ImGui FaustyShell${SHELL_PLATFORM})
endfunction()
